<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\bam.data.repositories\bam.data.repositories\bam.data.repositories.csproj" />
      <ProjectReference Include="..\..\bam.data\bam.data\bam.data.csproj" />
      <ProjectReference Include="..\..\bam.encryption\bam.encryption\bam.encryption.csproj" />
      <ProjectReference Include="..\..\bam.protocol\bam.protocol.data\bam.protocol.data.csproj" />
      <ProjectReference Include="..\..\bam.protocol\bam.protocol\bam.protocol.csproj" />
    </ItemGroup>

</Project>
