<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="$(BamFrameworkRoot)bam.data.repositories\bam.data.repositories\bam.data.repositories.csproj" />
      <ProjectReference Include="$(BamFrameworkRoot)bam.data\bam.data\bam.data.csproj" />
      <ProjectReference Include="$(BamFrameworkRoot)bam.encryption\bam.encryption\bam.encryption.csproj" />
      <ProjectReference Include="$(BamFrameworkRoot)bam.protocol\bam.protocol.data\bam.protocol.data.csproj" />
      <ProjectReference Include="$(BamFrameworkRoot)bam.protocol\bam.protocol\bam.protocol.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="Data\Local\BlobProfileDelegatedKeySetData.cs" />
    </ItemGroup>

</Project>
