<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>bam.blobs.distributed</RootNamespace>
        <IntermediatePackDir Condition=" '$(OS)' == 'Windows_NT' ">$(HOMEDRIVE)$(HOMEPATH)/.bam/build/pack/$(Configuration)/$(MSBuildThisFileName)/</IntermediatePackDir>
        <IntermediatePackDir Condition=" '$(OS)' == 'UNIX' ">$(HOME)/.bam/build/pack/$(Configuration)/$(MSBuildThisFileName)/</IntermediatePackDir>
    </PropertyGroup>
    <PropertyGroup>
        <OutputPath Condition=" '$(OS)' == 'Windows_NT' ">$(HOMEDRIVE)$(HOMEPATH)\.bam\build\$(Configuration)\$(MSBuildThisFileName)\</OutputPath>
        <OutputPath Condition=" '$(OS)' == 'UNIX' ">$(HOME)\.bam\build\$(Configuration)\$(MSBuildThisFileName)\</OutputPath>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include=".bam\" />
      <Folder Include="Data\" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="$(BamFrameworkRoot)bam.base\bam.base\bam.base.csproj" />
      <ProjectReference Include="$(BamFrameworkRoot)bam.data\bam.data\bam.data.csproj" />
      <ProjectReference Include="..\bam.blobs\bam.blobs.csproj" />
    </ItemGroup>

</Project>
